# ──────────────────────────────
#   FONT
# ──────────────────────────────
font=JetBrainsMono Nerd Font:size=18

# ──────────────────────────────
#   WINDOW BEHAVIOR
# ──────────────────────────────
pad=14x14

[csd]
preferred=none

[main]
shell=zsh

# ──────────────────────────────
#   SCROLLBACK
# ──────────────────────────────

[scrollback]
lines=5000


# ──────────────────────────────
#   COLORS
# ──────────────────────────────
[colors-dark]
alpha=1
background=1a1b26
foreground=bcbcbc
regular0=1c1c1c  # black
regular1=d75f5f  # red
regular2=87af87  # green
regular3=af875f  # yellow
regular4=87afaf  # blue
regular5=af87af  # magenta
regular6=5f8787  # cyan
regular7=bcbcbc  # white
bright0=585858   # bright black
bright1=5f8787   # bright red
bright2=87af87   # bright green
bright3=fff8d7   # bright yellow
bright4=87afaf   # bright blue
bright5=af87af   # bright magenta
bright6=87ffff   # bright cyan
bright7=ffffff   # bright white
